language: node_js
node_js:
  - "6"
sudo: required
env:
  global:
  - secure: DwaGHSzXBaLBIUx9TE0cQEE6m/tayx3eVj57/wYkkQi61+NEn0YlZe/w4st/4v6UAeerU4ezs0WnJ8CR+tiDpQTg2frN0jwAcoDdI8+s1fj3ScfWPaflTZJaIUyexFAv+ZUJw60dk0QvptbN87Cl8pLgBWuplVEy6RNKgGfBlWDMV+t6EfnZGbjaeCLVHnSB0/BT5rx5+23BdeIUqarUWJBh+zxHO3sXkxPC3WiAYN4Te2l/OiU252xjOGIfL0nMSKHnRcZ7wCsiOEH3+87X2BctA/p6xC/pmhRYkAzbT27s+6EYd2bzKVfPwiykqT/vYzWWq6xTz/cnO9BT0qAyzsds6Ny/OnOpr3SURSlyYxuz8fDXn5zCaXRj8ClvX8dKyTTzT80ViR7El5mGEqgnUnF1fQZoxMgIbRnGRvhaysGxVt2uP8qnG+Tcbu5UYGq7/HSvBy33UV49M+17IUig/ghgYi4kiLdZU+UDGh1XaD3MGFOHtJtiPNBs+uBA1EuSHKr5C6h5zo42G3r6BZa0yKBeJPIoxPV5aTI2Dv8w4D+BMygRPwoAQaUlDVMW6UW9bIAJmHb+yRmsWaPAFvHfIeZbsKBkhr5xk4Ai7RwYi4DvxqmYSnYO+n+cDOo0vbk4EexSpSco/EGBItPf5dK6N10XKvipA+BcM56KdO4s/xs=
  - secure: SHW+EvN6tpGe3hMFvHyy9eD4/+Pa68zwMwYqNgv8Llo4diI47TXQ2jZU4el9SeopFYYJQAp2MG7gaeSDGmWSv19fB49Gadlmw4U6G6W4GdAp0MmBgLSQSQjwT5DufSNi9uLmoIDMGAXQOXOob/SnPAW1p+MUS6t0ccO6qAUBHgqgVz0IEK9BCZLAKwJeaxy9+MCntiAkC+wmqDQnLRLWsDxQnk9Y5W/+1qmC9j681f+pG051Jq4WTn5+nwfzL5MM35SmAnT0CEix2XB8utv8QOsPSUsusqzXeT1oMM7MkNlI0f7De8/nz10FiKVUZLn0ajT47o49HLW7KZdoyjagsh614mwmJ+vpLxVpvqXoxIwrE1K3OsHs7zPsu1764E/4PdWFrDt1V88/8zVzarxGkjkMxeSIrST8n2zRPcCBRD2a32I5HHBf4mlmd9iDS6hLMY4emJ6hmKmiWSPoYvU/B3hYCv28FTMqNH5iJM7iW2D+cKHN8/jEJ4vu44vAJ17IMs+20ctT3btcjGpWUpVOsz2iJYg2ZLpWNAUXF4KkQqsD1sNKrmD86leL5QZ7vu6I0FMAZ2w8SxQ9cNHmgw5GpLQ6j6MqsmzEm8FOkAuz/azpcZmVSpyrOijXith0xwM+rLLPL/Jt/ZLzYbkk5GmhaizNUPkDAOXZcH45xqIZ+Cg=
  - GITHUB_EMAIL=jenkins@starschema.net
  - GITHUB_USER=jenkins-starschema
  - PACKAGE=bobj-access
  - OWNER=starschema
  - BUILD_DIR=/home/virtdb-demo/repo
  - BUILD_SCRIPTS_DIR=/home/virtdb-demo/scripts
before_install:
  - npm install
install:
  - npm install gulp
script:
  - gulp build
deploy:
  provider: npm
  email: virtdb-dev@virtdb.com
  api_key:
    secure: HIZn2hW9dkuXtmc+8VsgP7a7L9g7MpF9MOL9H/PyNCaPEKUPQwKB30ij4V0zPmkdZ40X2ePbUpwZqoT48xIY9+7ZFCFTt486/mJW+C/ph2rnRs0kgKpTV3kbnGZqz/YZE1wmxa21mzdKfMUgyVcFsXrKTQ1Y46lW/6y/AL16k9fTdyDFayMiytV82i0wix+c1kwtN4wd0ytq111PGBKGg1eQn8Cbyr7gGpjHXxSEPGNszfoPFp1MGrto/IfXW6C/VhSl28RAzf1/P4FHPmynVJwwnyGnuxbpEvjw6wRyUqeE0vsIy3gOT25AQ7nAzpOypTQnSkpfvKsYW0LqngJi9v2QzE5T5Jl62xYG0FgYls2YmtMydyH4gByL7irOLo6bVshfGy5Oqbx1hWTKYDSqKbb4WXMOBqx9crXp/U6o+XofnbSxTsn//zFAR0H2Kp5YAtH8wmJLCavRgtlu58RZ4dOhmLIW5wOCIxPKNe3ALnXqW9aoVdzsd7Ynm733GWRokrW63HnKeAPT8BXgW/YIATIU5dAd+bZ0UI+G41LhxVKPADeWNWjYqPWcwjrDQwJmhccldMdu+GlWxbRczn+h0943TU9YUybWi/+EEBc9tnJ0FAXgUDPb1DaZrnMABFXgz49E5PYtv2qiLdQrKzixbUopyEB/03t1Q5aBJ2Sbk6k=
  on:
    tags: true
    repo: starschema/bobj-access
