language: node_js
node_js:
  - "6"
sudo: required
env:
  global:
  - secure: DwaGHSzXBaLBIUx9TE0cQEE6m/tayx3eVj57/wYkkQi61+NEn0YlZe/w4st/4v6UAeerU4ezs0WnJ8CR+tiDpQTg2frN0jwAcoDdI8+s1fj3ScfWPaflTZJaIUyexFAv+ZUJw60dk0QvptbN87Cl8pLgBWuplVEy6RNKgGfBlWDMV+t6EfnZGbjaeCLVHnSB0/BT5rx5+23BdeIUqarUWJBh+zxHO3sXkxPC3WiAYN4Te2l/OiU252xjOGIfL0nMSKHnRcZ7wCsiOEH3+87X2BctA/p6xC/pmhRYkAzbT27s+6EYd2bzKVfPwiykqT/vYzWWq6xTz/cnO9BT0qAyzsds6Ny/OnOpr3SURSlyYxuz8fDXn5zCaXRj8ClvX8dKyTTzT80ViR7El5mGEqgnUnF1fQZoxMgIbRnGRvhaysGxVt2uP8qnG+Tcbu5UYGq7/HSvBy33UV49M+17IUig/ghgYi4kiLdZU+UDGh1XaD3MGFOHtJtiPNBs+uBA1EuSHKr5C6h5zo42G3r6BZa0yKBeJPIoxPV5aTI2Dv8w4D+BMygRPwoAQaUlDVMW6UW9bIAJmHb+yRmsWaPAFvHfIeZbsKBkhr5xk4Ai7RwYi4DvxqmYSnYO+n+cDOo0vbk4EexSpSco/EGBItPf5dK6N10XKvipA+BcM56KdO4s/xs=
  - secure: SHW+EvN6tpGe3hMFvHyy9eD4/+Pa68zwMwYqNgv8Llo4diI47TXQ2jZU4el9SeopFYYJQAp2MG7gaeSDGmWSv19fB49Gadlmw4U6G6W4GdAp0MmBgLSQSQjwT5DufSNi9uLmoIDMGAXQOXOob/SnPAW1p+MUS6t0ccO6qAUBHgqgVz0IEK9BCZLAKwJeaxy9+MCntiAkC+wmqDQnLRLWsDxQnk9Y5W/+1qmC9j681f+pG051Jq4WTn5+nwfzL5MM35SmAnT0CEix2XB8utv8QOsPSUsusqzXeT1oMM7MkNlI0f7De8/nz10FiKVUZLn0ajT47o49HLW7KZdoyjagsh614mwmJ+vpLxVpvqXoxIwrE1K3OsHs7zPsu1764E/4PdWFrDt1V88/8zVzarxGkjkMxeSIrST8n2zRPcCBRD2a32I5HHBf4mlmd9iDS6hLMY4emJ6hmKmiWSPoYvU/B3hYCv28FTMqNH5iJM7iW2D+cKHN8/jEJ4vu44vAJ17IMs+20ctT3btcjGpWUpVOsz2iJYg2ZLpWNAUXF4KkQqsD1sNKrmD86leL5QZ7vu6I0FMAZ2w8SxQ9cNHmgw5GpLQ6j6MqsmzEm8FOkAuz/azpcZmVSpyrOijXith0xwM+rLLPL/Jt/ZLzYbkk5GmhaizNUPkDAOXZcH45xqIZ+Cg=
  - GITHUB_EMAIL=jenkins@starschema.net
  - GITHUB_USER=jenkins-starschema
  - PACKAGE=bobj-access
  - OWNER=starschema
  - BUILD_DIR=/home/virtdb-demo/repo
  - BUILD_SCRIPTS_DIR=/home/virtdb-demo/scripts
before_install:
  - npm install
install:
  - npm install gulp
script:
  - gulp build
deploy:
  provider: npm
  email: jenkins@starschema.net
  api_key:
    secure: mfhMQ0MKU1TQncMrT5WQQDq5uOcbGhOf+Y/MlPHhan/L1pgfZq1ZLMnnnCH1ZVueGQX0/Ey9ANOXkv3cZb5oIFjtDFtUZ40T/ulAil5jtwsZsR4hXLqXiICHDAXA3O1cnYjdg+5p73H0DvJXJsRu3Ev1Or/ApmrKR+rfgXqwU5w0yC3AXxmsmr3OXHHdMK1P7wvKkbFpuftf6M/Xiu8MHwdGTk0s03G0Jtag67pJnCn29PyRGhRDSfSyv84MIBT+XIlAJZeOp7/f7B9nlcm/TyO0YPM38MMm5KcMCwqin8cga534S9zkaW6e9LpNwyx/cavyKH9VqTIwiqD9Hpc/CL4AyxDAdpX3Gx9wTfJlEWOJk1ESo4FqkPEXGGKsKG/YmhTq7uu4yKl/ROVDyJo1pXGbKPr/x5JcuwrhkqWNA9QOfCZaH0EqrKP/ZWfTnRDKekLCAtkyQsNMbt8U0duZZpgKOCoiSCdoW+f3ibKYKwWNoFco9SzqpVh0LKE/bqqVg+rrO7hXlw2a/rZEy3v4h6Re9zT0JPxycf++fow8bQ3cxi00wM/ztxYImMcvM4twhn6d6jWNdo1sbAVr252kEYSbc3yfZx9Lq3sGXfCe0PAromiV1f5MWS0rH/d2ckv+TaxrlewB3gRGr6yWT2OBZctQHmcdPD7Qn2IboNa1SOY=
  on:
    tags: true
    repo: starschema/bobj-access
